[package]
name = "outils"
version = "0.1.0"
authors = ["Oliver Uwira"]

[dependencies]
rand = "0.4.2"
bencher = "0.1.5"
lazy_static = "1.0.0"
slab = "0.4"

[[bench]]
name = "outils_benchmarks"
harness = false

[profile.bench]
opt-level = 3
debug = true 